camera_yaw_offset: -1.57

gui: false
debug: false
silent_debug: false

ang_rate_source: "imu" # "imu" / "odometry"
raw_output: true # should publish raw data?

analyze_duration: 1.0 # ??
scale_rotation: false # ??
scale_rot_magnitude: 49.9 # ??
scale_rot_output: "velocity"
d3d_method: "" # ??

store_video: false
video_path: "/dev/null"
video_fps: 30

optic_flow:

  max_processing_rate: 500
  method: 4
  scan_radius: 21
  step_size: 24
  frame_size: 480
  sample_point_size: 120
  filter_method: "allsac"

  apply_abs_bouding: true
  apply_rel_bouding: false

  scale_factor: 1.0

  rotation_correction: true
  tilt_correction: true

  ransac:
    num_of_chosen: 2
    num_of_iter: 50
    threshold_rad: 1.0

  filtering:
    last_speeds_size: 60

constraints:
  max_pixel_speed: 80

  max_horizontal_speed: 5.0
  max_horizontal_acceleration: 1.5

  max_vertical_speed: 2.0

  max_yaw_rate: 1.0

  speed_noise: 1.5
